// <auto-generated />
namespace Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class data_annotations1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(data_annotations1));
        
        string IMigrationMetadata.Id
        {
            get { return "201609061440020_data_annotations1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
